# Generated by Django 2.0.5 on 2018-05-19 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trs_id', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
                ('transaction_datetime', models.DateTimeField()),
                ('status', models.CharField(max_length=64)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Booking')),
            ],
        ),
    ]
